const constants={
    SET_CERT:"SET_CERT",
    SET_RFC:"SET_RFC",
    SET_KEY:"SET_KEY",
    SET_CERT_CONTENIDO:"SET_CERT_CONTENIDO",
    SET_KEY_CONTENIDO:"SET_KEY_CONTENIDO",
    SET_CONTRASENIA:"SET_CONTRASENIA",
	SET_VERIFICADO:"SET_VERIFICADO",

	ARCHIVOS_CONTENIDO:"ARCHIVOS_CONTENIDO"

}

export default constants